### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by thomaslc66** [fortunar/react-sidemenu#20]
I get this error when import like in the image

![image](https://user-images.githubusercontent.com/9827392/59753690-f6796500-9284-11e9-9f23-bbd6b7fa0a87.png)

![image](https://user-images.githubusercontent.com/9827392/59753646-e06ba480-9284-11e9-9019-14f20e890c8c.png)

but the component and the app render ok when i do `import SideMenu from 'react-sidemenu`

**Comment by teanz** [comment]
Your import can be like so -  import SideMenu, { Item } from 'react-sidemenu' if using react components for item.
