### ISSUE TITLE
Active item doesn't toggle when collapse={false}

### ISSUE THREAD

**Issue by elgs** [fortunar/react-sidemenu#3]
It seems when `collapse={false}`, the old active item doesn't become inactive when a new item is clicked.

**Comment by fortunar** [comment]
Exactly, that is desired effect of the property.

**Comment by elgs** [comment]
I think semantically collapse and toggle active item should be two different things. Do you think there's any chance to put them into separate options?

By the way, can you please leave this thread open for a while for further discussion? Thanks.
