### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by s1012602** [fortunar/react-sidemenu#6]
> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

This warning direct to `node_modules\react-sidemenu\lib\SideMenu.js:335`
```
SideMenu.propTypes = {
  items: _react.PropTypes.array,
  onMenuItemClick: _react.PropTypes.func,
  renderMenuItemContent: _react.PropTypes.func,
  theme: _react.PropTypes.string,
  collapse: _react.PropTypes.bool,
  rtl: _react.PropTypes.bool,
  activeItem: _react.PropTypes.string
};
```

Could we update `react.PropTypes` to `Proptypes`?

**Comment by sapkra** [comment]
You changed it in the source file but it is still wrong in the lib file. Can you please update it?

**Comment by fortunar** [comment]
@sapkra Done
